In [58]:
import numpy as np
import pandas as pd

In [59]:
meta_data = pd.read_csv('data\metadata_train_challenge.csv')

In [60]:
df = np.load('data/npy/audio_data.npy', allow_pickle=True)
df[0:2]

array([AudioData(name='001ba082-6316-4caa-b94e-df5e1ef7141c.wav', features=AudioFeatures(wav=array(shape=(51597,), dtype=float32), mfccs=array(shape=(20, 3833), dtype=float32)), sampling_rate=22050),
       AudioData(name='003321df-a7ce-43b6-b5ef-8588832fcac8.wav', features=AudioFeatures(wav=array(shape=(218295,), dtype=float32), mfccs=array(shape=(20, 3833), dtype=float32)), sampling_rate=22050)],
      dtype=object)

In [61]:
meta_data.values[0]

array(['3284bcf1-2446-4f3a-ac66-14c76b294177', 'male', 23.0, 0,
       '3284bcf1-2446-4f3a-ac66-14c76b294177.wav'], dtype=object)

In [62]:
def transform(audio_data, meta_data):
    result = []
    audio_features = dict()
    # get feature in audio_data
    for i in range(len(audio_data)):
        name = audio_data[i].name
        features = audio_data[i].features.mfccs.reshape(-1)
        audio_features[name] = features
    #-----------------------------
    for item in meta_data.values:
        tmp = []
        if item[1]=='male':
            tmp.append(1)
        else: tmp.append(0)
        tmp.append(item[2])
        tmp.append(item[3])
        tmp += audio_features[item[4]].tolist()
        result.append(np.array(tmp, dtype=float))
    return np.array(result)

In [63]:
x = transform(df, meta_data)
print(x)

[[ 1. 23.  0. ...  0.  0.  0.]
 [ 0. nan  0. ...  0.  0.  0.]
 [ 0. nan  0. ...  0.  0.  0.]
 ...
 [ 1. 52.  0. ...  0.  0.  0.]
 [ 0. 23.  1. ...  0.  0.  0.]
 [ 0. 40.  1. ...  0.  0.  0.]]


In [66]:
np.save('data\data_transform\meta_data.npy', x)

In [65]:
meta_transforms = np.load('data\data_transform\meta_data.npy', allow_pickle=True)
meta_transforms[0:2]

array([[ 1., 23.,  0., ...,  0.,  0.,  0.],
       [ 0., nan,  0., ...,  0.,  0.,  0.]])